In [43]:
from pathlib import Path
import numpy as np
np.set_printoptions(precision=2)

# path = Path("/home/cra80/Projects/threestudio-sketch/outputs/mvdream+sd-increased_weights/teapot_001@20240409-035530/save/open3d/extrinsics")
# name = "{:06d}.log".format(105)

# path = path / name

# # Load the data from the file
# with open(path, 'r') as file:
#     lines = file.readlines()

# # Parse the lines into a numpy array
# matrix = np.array([list(map(float, line.split())) for line in lines[1:]])

# String representation of the data
data_str = """0.6622468269	0.3453573853	-0.6649501792	2.1576304963
-0.0657341728	0.9108003932	0.4075784509	1.2549109293
0.7463989820	-0.2262069937	0.6258774298	0.1949499389
0.0000000000	0.0000000000	0.0000000000	1.0000000000"""
matrix = np.array([[float(num) for num in line.split()] for line in data_str.split('\n')])

print(matrix)
matrix = matrix.T.flatten()

for value in matrix:
    print(value, end=",\n")

[[ 1.    0.07 -0.06  1.71]
 [-0.07  1.    0.05  1.41]
 [ 0.07 -0.04  1.   -0.35]
 [ 0.    0.    0.    1.  ]]
0.9952207825,
-0.0701019649,
0.0679793744,
0.0,
0.0731495135,
0.9963749464,
-0.0434252669,
0.0,
-0.0646888104,
0.0481903926,
0.9967417319,
0.0,
1.7128454645,
1.4146349002,
-0.3505739308,
1.0,
